### ISSUE TITLE
config.yml activate method?

### ISSUE THREAD

**Issue by GWan1234** [Depau/wi-se-sw#3]
Thanks for this project and your hard work.
I use VSCode to compile, how to activate config.yml.example?

**Comment by depau** [comment]
The program configuration is a bit complicated since one of my goals was to allow for configuring many devices at once.

Check [Building and flashing](https://github.com/depau/wi-se-sw#building-and-flashing) in the README.

Follow the steps to install the Python dependencies to run the `builder.py` script. Then, as you can see at the end of the section, you can run `./builder.py devconf --example` to generate a development config for use with VScode or PlatformIO IDE.

Keep in mind that `config.h` and `platformio.ini` are generated by the script and if you edit them and re-run the script it will overwrite them.

Let me know if you have any questions.

**Comment by GWan1234** [comment]
(venv) u@u-Standard-PC-i440FX-PIIX-1996:~/diy/wi-se-sw$ ./builder.py upload
= RUNNING ACTION upload FOR device_name =====================================================================================================================
Generate include/config.h
Generate platformio.ini
Traceback (most recent call last):
  File "/home/u/diy/wi-se-sw/./builder.py", line 528, in main
    builder.build_and_upload()
  File "/home/u/diy/wi-se-sw/./builder.py", line 385, in build_and_upload
    subprocess.run(['platformio', '-c', 'clion', 'run', '--target', 'upload'], cwd=self.builder_dir, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'platformio'
= FAILED - device_name ======================================================================================================================================

FAILED BUILDS - Recap

+ device_name

    Traceback (most recent call last):
      File "/home/u/diy/wi-se-sw/./builder.py", line 528, in main
        builder.build_and_upload()
      File "/home/u/diy/wi-se-sw/./builder.py", line 385, in build_and_upload
        subprocess.run(['platformio', '-c', 'clion', 'run', '--target', 'upload'], cwd=self.builder_dir, check=True)
      File "/usr/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'platformio'


(venv) u@u-Standard-PC-i440FX-PIIX-1996:~/diy/wi-se-sw$

**Comment by depau** [comment]
Did you install PlatformIO Core? https://platformio.org/install/cli

**Comment by GWan1234** [comment]
Thanks for your reply, it's been solved, really fascinating.
